### ISSUE TITLE
Make a new `part` for julia packages related to software engineering

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#11]
Right now the `_toc.yml` is
```yml
- part: Packages and Software Engineering in Julia
  chapters:
  - file: more_julia/generic_programming
  - file: more_julia/general_packages
  - file: more_julia/data_statistical_packages
  - file: more_julia/optimization_solver_packages
  - file: more_julia/tools_editors
  - file: more_julia/version_control
  - file: more_julia/testing
  - file: more_julia/need_for_speed
```
And I want to is create a new folder, `software_engineering` and move them around into two parts
```yml
- part: Package Ecosystem
  chapters:
  - file: more_julia/generic_programming
  - file: more_julia/general_packages
  - file: more_julia/data_statistical_packages
  - file: more_julia/optimization_solver_packages
- part: Software Engineering
-   chapters:
  - file: software_engineering/tools_editors
  - file: software_engineering/version_control
  - file: software_engineering/testing
  - file: software_engineering/need_for_speed
```
